### ISSUE TITLE
Invalid Origin Error

### ISSUE THREAD

**Issue by erikroblarsen** [adyen-examples/adyen-react-online-payments#5]
When I run this application, I'm unable to test out any of the payment methods due to an "Invalid Origin" error. When I try to test out a credit card, the card fields all show "Invalid Origin" - see the image I've added. 

I've checked my customer area, and I have both http://localhost:8080 and http://localhost:3000 setup as the allowed origins. Any idea what I'm doing wrong?

![image](https://user-images.githubusercontent.com/51800275/105877290-ce5bf700-5fcd-11eb-988e-20652becb3ec.png)

**Comment by sajjad606** [comment]
hi, if you are in iran you can pay any forign payments via our web site.
سایت EPAY 724 | خدمات ارزی بین الملل (https://bit.ly/3uieWwW) (سایت EPAY 724 | خدمات ارزی بین الملل (https://epay724.com))
online payments for application fees, buying gift cards, international exams fees are easier than ever ….

**Comment by deepu105** [comment]
Seems like you haven't configured the client key properly. Please follow the Readme and setup your client key (https://docs.adyen.com/user-management/client-side-authentication) Remember to add `http://localhost:3000` as an origin for client key

**Comment by dash7ou** [comment]
Hi @erikroblarsen why I got a 401 error when getPaymentMethods request called, Can u help me pls?

**Comment by deepu105** [comment]
@dash7ou make sure you have configured your API_KEY following the Readme file on this repo

**Comment by dash7ou** [comment]
@deepu105 I have setup it in right way Iam sure and give me 401 error, why ???

**Comment by dash7ou** [comment]
@deepu105 Can u help me in that and save my day pls?

**Comment by deepu105** [comment]
What is the exact error you get on server side can paste the log here?

**Comment by dash7ou** [comment]
@deepu105 server side response 
HttpClientException {
  statusCode: 401,
  name: 'HttpClientException',
  message: 'HTTP Exception: 401. 401: HTTP Status Response - Unauthorized',
  responseHeaders: {
    date: 'Sat, 24 Apr 2021 12:42:42 GMT',
    server: 'Apache',
    'set-cookie': [
      'JSESSIONID=767C6ADACD0F39D495D3E4049DDC669C.test8e; Path=/checkout; Secure; HttpOnly'
    ],
    'www-authenticate': 'BASIC realm="Adyen PAL Service Authentication"',
    connection: 'close',
    'transfer-encoding': 'chunked',
    'content-type': 'application/json'
  },
  responseBody: '{"status":401,"errorCode":"000","message":"HTTP Status Response - Unauthorized","errorType":"security"}',
  errorCode: '000'
}

**Comment by deepu105** [comment]
Well, it looks like an issue with your API key, either missing key or wrong key. (could also be any of these if you have made changes to the app here https://docs.adyen.com/development-resources/error-codes#000-unknown ) Assuming you have followed the below before starting the app, I would suggest to create a new API key and try with that. If its still gives the same error then there could be an issue with your account and you would need to reach out to Adyen support to check it

1. Create a `./.env` file with your [API key](https://docs.adyen.com/user-management/how-to-get-the-api-key), [Client Key](https://docs.adyen.com/user-management/client-side-authentication) - Remember to add `http://localhost:3000` as an origin for client key, and merchant account name (all credentials are in string format):

```
API_KEY="your_API_key_here"
MERCHANT_ACCOUNT="your_merchant_account_here"
REACT_APP_CLIENT_KEY="your_client_key_here"
ADYEN_HMAC_KEY=yourNotificationSetupHMACkey
```

**Comment by dash7ou** [comment]
@deepu105 
No I have discovered the error this morning because I added my key in .env file like that
API_KEY="your_API_key_here"
the right Way is
API_KEY=your_API_key_here
And every thing working fine now :-)

**Comment by deepu105** [comment]
Thats strange. Ideally it shouldn't matter

**Comment by dash7ou** [comment]
@deepu105 That what I am saying to my self when I fixed it, but I do not have time to think about that and why that happened actually, If u want to know how I discover that I have generated a lot of keys then I see one of the keys contain $ this broken "" color in .env file so i have remove it ("") and its working fine :)

**Comment by dash7ou** [comment]
Another strange error, I am using the test card number from Adyen doc.
 In test mode, Adyen API gives me that 
{
  pspReference: '852619356836576D',
  refusalReason: 'FRAUD-CANCELLED',
  resultCode: 'Cancelled',
  refusalReasonCode: '22',
  merchantReference: 'ec3eb8dc-2de2-42f1-81b5-b87e23f1b260'
}
mean: The risk check flagged the transaction as fraudulent (risk score >= 100); therefore, the operation is canceled, so how can I pass that  :joy, I am in testing mooooodd Adyen

**Comment by dash7ou** [comment]
I have solved it by trust my Ip with card number because my country and card country is different
from  Transactions > Payments then trust IP from there :P

**Comment by PratimaGurav** [comment]
Hello, Can anyone help me with the error Missing CLIENT_KEY in .env
I have updated it in .env still receiving error
